[workspace]
resolver = "2"
members = [
	"tsclientlib",
	"tsproto",
	"utils/ts-bookkeeping",
	"utils/tsproto-packets",
	"utils/tsproto-structs",
	"utils/tsproto-types",
]

[patch.crates-io]
native-tls = { path = "tsclientlib/vendor/native-tls-0.2.17" }
